### ISSUE TITLE
Not parsing DateTimes when parsing the SKON file?

### ISSUE THREAD

**Issue by NogginBops** [SpaceKrakens/SKON.NET#17]
I think we would be able to parse DateTimes more efficiently if we just read them as strings and then parse them only if they are queried. This way we can remove complexity from the parser and make it faster.

**Comment by vogonistic** [comment]
I think it's a good optimization. Works very well since people have to request the value as a DateTime.

**Comment by NogginBops** [comment]
Should DateTime be verified to be in the right format when parsing? or should we just accept everything and see if it's valid when we parse it?

**Comment by Tranberry** [comment]
Isn't that something the highlight should bother with  :wink: @longtomjr

**Comment by longtomjr** [comment]
I think that the earlier an error in the file is spotted is better.

**Comment by NogginBops** [comment]
I agree with @longtomjr. And if we're already checking the format I don't think it's any less performant to just parsing it.

**Comment by NogginBops** [comment]
Closing this as there is no benefit in implementing this.
